version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always 
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx:/etc/nginx
      - ./video:/var/www/video
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot  
    depends_on:
      - vast-provider
  vast-provider:
    container_name: vast-provider
    image: prebidlab/vast-provider:0.0.6
    logging:
      options:
        max-size: "500"
        max-file: "10"  
    restart: always
    volumes: 
      - ./data/items.json:/items.json
      - ./data/stats.json:/stats.json
    environment:
      SERVER_LISTEN_NETWORK: tcp4
      SERVER_LISTEN_ADDR: :8080
      BASE_URL: https://video.roiconnector.xyz      
